name: "Native Rust Play Store Upload"
description: "Upload to Google Play without Docker or Node.js"
inputs:
  packageName:
    required: true
    description: "Android package name"
  track:
    required: true
    description: "Release track (e.g. production, internal)"
  status:
    required: false
    default: "completed"
    description: "Release status (e.g. completed, draft, inProgress)"
  releaseFile:
    required: true
    description: "Path to .aab or .apk"
  serviceAccountJsonPlainText:
    required: true
    description: "GCP Service Account JSON"

runs:
  using: "composite"
  steps:
    - name: Download Binary
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TARGET_TAG="${{ github.action_ref }}"
        if [[ -z "$TARGET_TAG" || "$TARGET_TAG" == "main" ]]; then
          echo "Downloading latest release..."
          gh release download --repo ${{ github.action_repository }} --pattern "gp-upload-action"
        else
          echo "Downloading release for tag $TARGET_TAG..."
          # gh CLI автоматически разрешает теги, включая мажорные
          gh release download "$TARGET_TAG" --repo ${{ github.action_repository }} --pattern "gp-upload-action"
        fi
        chmod +x gp-upload-action

    - name: Execute Action
      shell: bash
      env:
        INPUT_PACKAGENAME: ${{ inputs.packageName }}
        INPUT_TRACK: ${{ inputs.track }}
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_RELEASEFILE: ${{ inputs.releaseFile }}
        INPUT_SERVICEACCOUNTJSONPLAINTEXT: ${{ inputs.serviceAccountJsonPlainText }}
      run: ./gp-upload-action
